classDiagram
    A: someAbstractMethod()*
    A: someAbstractMethodWithReturn() int*
    A: someStaticMethod()$
    A: someStaticMethodWithReturn() int$
    A: someStaticAbstractMethodWithReturn() int*
    class B {
        someAbstractMethod()*
        someAbstractMethodWithReturn() int*
        someStaticMethod()$
        someStaticMethodWithReturn() int$
        someStaticAbstractMethodWithReturn() int*
    }