classDiagram
    %% Comment at the diagram level
    namespace n {
        class Shape {
            <<interface>>
            noOfVertices
            %% Comment at the class level
            draw()
        }
        %% Comment at the namespace level
    }