flowchart LR
    nodeId1 --> nodeId2
    classDef className fill:#f9f,stroke:#333,stroke-width:4px;
    classDef firstClassName,secondClassName font-size:12pt;
    class nodeId1 className
    class nodeId1,nodeId2 className